name: Sync to Confluence
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

      - name: Publish Markdown to Confluence
        uses: markdown-confluence/publish-action@v5
        with:
          confluenceBaseUrl: "https://awaysonwatkins.atlassian.net"
          confluenceParentId: "1277953"
          atlassianUserName: ${{ secrets.CONFLUENCE_EMAIL }}
          atlassianApiToken: ${{ secrets.CONFLUENCE_API_TOKEN }}
          folderToPublish: "docs"
