name: Sync to Confluence

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**' # Only run if docs change

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Sync to Confluence
        uses: MaikV/markdown-to-confluence@v4
        with:
          confluenceBaseUrl: '${{ secrets.CONFLUENCE_BASE_URL }}'
          confluenceParentId: '${{ secrets.CONFLUENCE_ROOT_PAGE_ID }}'
          atlassianUserName: '${{ secrets.CONFLUENCE_EMAIL }}'
          atlassianApiToken: '${{ secrets.CONFLUENCE_API_TOKEN }}'
          folderToPublish: 'docs'
